// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processDropReason uint32

const (
	processDropReasonDROP_RINGBUF_FULL processDropReason = 0
	processDropReasonDROP_REASON_MAX   processDropReason = 1
)

type processEvent struct {
	_               structs.HostLayout
	Type            uint32
	Pid             uint32
	Tgid            uint32
	Ppid            uint32
	Uid             uint32
	Gid             uint32
	Timestamp       uint64
	CgroupId        uint64
	StartTime       uint64
	ParentStartTime uint64
}

type processEventType uint32

const (
	processEventTypeEVENT_EXEC processEventType = 1
	processEventTypeEVENT_FORK processEventType = 2
	processEventTypeEVENT_EXIT processEventType = 3
)

type processExecEvent struct {
	_                 structs.HostLayout
	Hdr               processEvent
	Comm              [16]uint8
	Filename          [512]uint8
	ArgvLen           uint32
	ArgvTruncated     uint8
	ArgvReadFailed    uint8
	FilenameTruncated uint8
	Pad               uint8
	Argv              [4096]uint8
}

type processExitEvent struct {
	_        structs.HostLayout
	Hdr      processEvent
	Comm     [16]uint8
	ExitCode uint32
	Pad      uint32
}

type processForkEvent struct {
	_    structs.HostLayout
	Hdr  processEvent
	Comm [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	processMapDropCount        = "drop_count"
	processMapEvents           = "events"
	processMapTargetCgroups    = "target_cgroups"
	processProgHandleExec      = "handle_exec"
	processProgHandleExit      = "handle_exit"
	processProgHandleFork      = "handle_fork"
	processVarUnusedDropReason = "_unused_drop_reason"
	processVarUnusedEvent      = "_unused_event"
	processVarUnusedEventType  = "_unused_event_type"
	processVarUnusedExecEvent  = "_unused_exec_event"
	processVarUnusedExitEvent  = "_unused_exit_event"
	processVarUnusedForkEvent  = "_unused_fork_event"
	processVarModeHost         = "mode_host"
)

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
	processVariableSpecs
}

// processProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	HandleExec *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork *ebpf.ProgramSpec `ebpf:"handle_fork"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	DropCount     *ebpf.MapSpec `ebpf:"drop_count"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	TargetCgroups *ebpf.MapSpec `ebpf:"target_cgroups"`
}

// processVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processVariableSpecs struct {
	UnusedDropReason *ebpf.VariableSpec `ebpf:"_unused_drop_reason"`
	UnusedEvent      *ebpf.VariableSpec `ebpf:"_unused_event"`
	UnusedEventType  *ebpf.VariableSpec `ebpf:"_unused_event_type"`
	UnusedExecEvent  *ebpf.VariableSpec `ebpf:"_unused_exec_event"`
	UnusedExitEvent  *ebpf.VariableSpec `ebpf:"_unused_exit_event"`
	UnusedForkEvent  *ebpf.VariableSpec `ebpf:"_unused_fork_event"`
	ModeHost         *ebpf.VariableSpec `ebpf:"mode_host"`
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
	processVariables
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	DropCount     *ebpf.Map `ebpf:"drop_count"`
	Events        *ebpf.Map `ebpf:"events"`
	TargetCgroups *ebpf.Map `ebpf:"target_cgroups"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.DropCount,
		m.Events,
		m.TargetCgroups,
	)
}

// processVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processVariables struct {
	UnusedDropReason *ebpf.Variable `ebpf:"_unused_drop_reason"`
	UnusedEvent      *ebpf.Variable `ebpf:"_unused_event"`
	UnusedEventType  *ebpf.Variable `ebpf:"_unused_event_type"`
	UnusedExecEvent  *ebpf.Variable `ebpf:"_unused_exec_event"`
	UnusedExitEvent  *ebpf.Variable `ebpf:"_unused_exit_event"`
	UnusedForkEvent  *ebpf.Variable `ebpf:"_unused_fork_event"`
	ModeHost         *ebpf.Variable `ebpf:"mode_host"`
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	HandleExec *ebpf.Program `ebpf:"handle_exec"`
	HandleExit *ebpf.Program `ebpf:"handle_exit"`
	HandleFork *ebpf.Program `ebpf:"handle_fork"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.HandleExec,
		p.HandleExit,
		p.HandleFork,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_x86_bpfel.o
var _ProcessBytes []byte
